<!DOCTYPE html>
<html  dir="ltr" lang="en" xml:lang="en">
<head>
    <title>163_GIIGSI10_26020_01: Presentación (Temario, Evaluación....)</title>
    <link rel="shortcut icon" href="https://egela.ehu.es/theme/image.php/standard/theme/1419846478/favicon" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="moodle, 163_GIIGSI10_26020_01: Presentación (Temario, Evaluación....)" />
<script type="text/javascript">
//<![CDATA[
var M = {}; M.yui = {};
M.pageloadstarttime = new Date();
M.cfg = {"wwwroot":"https:\/\/egela.ehu.es","sesskey":"An6hiqTdTt","loadingicon":"https:\/\/egela.ehu.es\/theme\/image.php\/standard\/core\/1419846478\/i\/loading_small","themerev":"1419846478","slasharguments":1,"theme":"standard","jsrev":"1419846478","svgicons":true};var yui1ConfigFn = function(me) {if(/-skin|reset|fonts|grids|base/.test(me.name)){me.type='css';me.path=me.path.replace(/\.js/,'.css');me.path=me.path.replace(/\/yui2-skin/,'/assets/skins/sam/yui2-skin');}};
var yui2ConfigFn = function(me) {var p = me.path, b = me.name.replace(/^moodle-/,'').split('-', 3), n = b.pop();if (/(skin|core)/.test(n)) {n = b.pop();me.type = 'css';};me.path = b.join('-')+'/'+n+'/'+n;if(me.type !== 'css'){me.path=me.path+'-min';};me.path=me.path+'.'+me.type;};
YUI_config = {"debug":false,"base":"https:\/\/egela.ehu.es\/lib\/yuilib\/3.9.1\/build\/","comboBase":"https:\/\/egela.ehu.es\/theme\/yui_combo.php?","combine":true,"filter":null,"insertBefore":"firstthemesheet","groups":{"yui2":{"base":"https:\/\/egela.ehu.es\/lib\/yuilib\/2in3\/2.9.0\/build\/","comboBase":"https:\/\/egela.ehu.es\/theme\/yui_combo.php?","combine":true,"ext":false,"root":"2in3\/2.9.0\/build\/","patterns":{"yui2-":{"group":"yui2","configFn":yui1ConfigFn}}},"moodle":{"name":"moodle","base":"https:\/\/egela.ehu.es\/theme\/yui_combo.php?moodle\/1419846478\/","combine":true,"comboBase":"https:\/\/egela.ehu.es\/theme\/yui_combo.php?","ext":false,"root":"moodle\/1419846478\/","patterns":{"moodle-":{"group":"moodle","configFn":yui2ConfigFn}},"modules":{"moodle-core-tooltip":{"requires":["base","node","io-base","moodle-core-notification","json-parse","widget-position","widget-position-align","event-outside","cache"]},"moodle-core-blocks":{"requires":["base","node","io","dom","dd","dd-scroll","moodle-core-dragdrop","moodle-core-notification"]},"moodle-core-formautosubmit":{"requires":["base","event-key"]},"moodle-core-notification":{"requires":["base","node","panel","event-key","dd-plugin"]},"moodle-core-popuphelp":{"requires":["moodle-core-tooltip"]},"moodle-core-chooserdialogue":{"requires":["base","panel","moodle-core-notification"]},"moodle-core-formchangechecker":{"requires":["base","event-focus"]},"moodle-calendar-eventmanager":{"requires":["base","node","event-mouseenter","overlay","moodle-calendar-eventmanager-skin"]},"moodle-course-categoryexpander":{"requires":["node","event-key"]},"moodle-mod_quiz-autosave":{"requires":["base","node","event","event-valuechange","node-event-delegate","io-form"]},"moodle-block_navigation-navigation":{"requires":["base","core_dock","io-base","node","dom","event-custom","event-delegate","json-parse"]},"moodle-filter_glossary-autolinker":{"requires":["base","node","io-base","json-parse","event-delegate","overlay","moodle-core-notification"]},"moodle-editor_tinymce-collapse":{"requires":["base","node","dom"]},"moodle-theme_bootstrapbase-bootstrap":{"requires":["node","selector-css3"]}}}},"modules":{"core_filepicker":{"name":"core_filepicker","fullpath":"https:\/\/egela.ehu.es\/lib\/javascript.php\/1419846478\/repository\/filepicker.js","requires":["base","node","node-event-simulate","json","async-queue","io-base","io-upload-iframe","io-form","yui2-treeview","panel","cookie","datatable","datatable-sort","resize-plugin","dd-plugin","escape","moodle-core_filepicker"]},"core_dock":{"name":"core_dock","fullpath":"https:\/\/egela.ehu.es\/lib\/javascript.php\/1419846478\/blocks\/dock.js","requires":["base","node","event-custom","event-mouseenter","event-resize","escape"]}}};
M.yui.loader = {modules: {}};

//]]>
</script>
<link rel="stylesheet" type="text/css" href="https://egela.ehu.es/theme/yui_combo.php?3.9.1/build/cssreset/cssreset-min.css&amp;3.9.1/build/cssfonts/cssfonts-min.css&amp;3.9.1/build/cssgrids/cssgrids-min.css&amp;3.9.1/build/cssbase/cssbase-min.css" /><script type="text/javascript" src="https://egela.ehu.es/theme/yui_combo.php?3.9.1/build/simpleyui/simpleyui-min.js&amp;3.9.1/build/loader/loader-min.js"></script><script id="firstthemesheet" type="text/css">/** Required in order to fix style inclusion problems in IE with YUI **/</script><link rel="stylesheet" type="text/css" href="https://egela.ehu.es/theme/styles.php/standard/1419846478/all" />
<script type="text/javascript" src="https://egela.ehu.es/lib/javascript.php/1419846478/lib/javascript-static.js"></script>
</head>
<body id="page-mod-resource-view" class="format-topics  path-mod path-mod-resource gecko dir-ltr lang-en yui-skin-sam yui3-skin-sam egela-ehu-es pagelayout-incourse course-343 context-15692 cmid-10351 category-530 side-pre-only">
<div class="skiplinks"><a class="skip" href="#maincontent">Skip to main content</a></div>
<script type="text/javascript">
//<![CDATA[
document.body.className += ' jsenabled';
//]]>
</script>

<div id="page">
    <div id="page-header">
                <h1 class="headermain">Bases de Datos</h1>
        <div class="headermenu"><div class="logininfo">You are logged in as <a href="https://egela.ehu.es/user/profile.php?id=11850" title="View profile">Javier Martín Salvatierra</a> (<a href="https://egela.ehu.es/login/logout.php?sesskey=An6hiqTdTt">Logout</a>)</div></div>                                    <div class="navbar clearfix">
                <div class="breadcrumb"><span class="accesshide">Page path</span><ul role="navigation"><li><a href="https://egela.ehu.es/">Home</a></li><li> <span class="accesshide " ><span class="arrow_text">/</span>&nbsp;</span><span class="arrow sep">&#x25BA;</span> <a href="https://egela.ehu.es/my/">My courses</a></li><li> <span class="accesshide " ><span class="arrow_text">/</span>&nbsp;</span><span class="arrow sep">&#x25BA;</span> <a href="https://egela.ehu.es/course/index.php?categoryid=2">Estudios de Grado</a></li><li> <span class="accesshide " ><span class="arrow_text">/</span>&nbsp;</span><span class="arrow sep">&#x25BA;</span> <a href="https://egela.ehu.es/course/index.php?categoryid=4">Campus de Alava</a></li><li> <span class="accesshide " ><span class="arrow_text">/</span>&nbsp;</span><span class="arrow sep">&#x25BA;</span> <a href="https://egela.ehu.es/course/index.php?categoryid=18">Escuela Universitaria de Ingeniería de Vitoria-Gasteiz</a></li><li> <span class="accesshide " ><span class="arrow_text">/</span>&nbsp;</span><span class="arrow sep">&#x25BA;</span> <a href="https://egela.ehu.es/course/index.php?categoryid=209">Grado en Ingeniería Informática de Gestión y Sistemas de Información</a></li><li> <span class="accesshide " ><span class="arrow_text">/</span>&nbsp;</span><span class="arrow sep">&#x25BA;</span> <a href="https://egela.ehu.es/course/index.php?categoryid=530">Curso 2º</a></li><li> <span class="accesshide " ><span class="arrow_text">/</span>&nbsp;</span><span class="arrow sep">&#x25BA;</span> <a title="Bases de Datos" href="https://egela.ehu.es/course/view.php?id=343">163_GIIGSI10_26020_01</a></li><li> <span class="accesshide " ><span class="arrow_text">/</span>&nbsp;</span><span class="arrow sep">&#x25BA;</span> <span tabindex="0">Topic 1</span></li><li> <span class="accesshide " ><span class="arrow_text">/</span>&nbsp;</span><span class="arrow sep">&#x25BA;</span> <a title="File" href="https://egela.ehu.es/mod/resource/view.php?id=10351" id="action_link552ff7033de3a2">Presentación (Temario, Evaluación....)</a></li></ul></div>
                <div class="navbutton"> </div>
            </div>
            </div>
<!-- END OF HEADER -->

    <div id="page-content">
        <div id="region-main-box">
            <div id="region-post-box">

                <div id="region-main-wrap">
                    <div id="region-main">
                        <div class="region-content">
                                                        <div role="main"><span id="maincontent"></span><h2 id="resourceheading" class="main">Presentación (Temario, Evaluación....)</h2><div id="resourceintro" class="box mod_introbox"><div class="no-overflow"><p>Temario, sistema de evaluación...</p></div></div><div class="resourceworkaround">Click <a href="https://egela.ehu.es/pluginfile.php/15692/mod_resource/content/2/presentacion_2014.pdf" onclick="window.open('https://egela.ehu.es/pluginfile.php/15692/mod_resource/content/2/presentacion_2014.pdf', '', 'width=620,height=450,toolbar=no,location=no,menubar=no,copyhistory=no,status=no,directories=no,scrollbars=yes,resizable=yes'); return false;">presentacion_2014.pdf</a> link to view the file.</div></div>                                                    </div>
                    </div>
                </div>

                                <div id="region-pre" class="block-region">
                    <div class="region-content">
                            <a href="#sb-1" class="skip-block">Skip Navigation</a><div id="inst4" class="block_navigation  block" role="navigation" aria-labelledby="instance-4-header"><div class="header"><div class="title"><div class="block_action"></div><h2 id="instance-4-header">Navigation</h2></div></div><div class="content"><ul class="block_tree list"><li class="type_unknown depth_1 contains_branch" aria-expanded="true"><p class="tree_item branch canexpand navigation_node"><a href="https://egela.ehu.es/">Home</a></p><ul><li class="type_setting depth_2 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/my/"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />My home</a></p></li>
<li class="type_course depth_2 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch"><span title="eGELA 2014-15 UPV/EHU" tabindex="0">Site pages</span></p><ul><li class="type_custom depth_3 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/blog/index.php?courseid=0"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Site blogs</a></p></li>
<li class="type_custom depth_3 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/tag/search.php"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Tags</a></p></li>
<li class="type_custom depth_3 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/calendar/view.php?view=month"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Calendar</a></p></li>
<li class="type_activity depth_3 item_with_icon"><p class="tree_item leaf hasicon"><a title="Forum" href="https://egela.ehu.es/mod/forum/view.php?id=169134"><img alt="Forum" class="smallicon navicon" title="Forum" src="https://egela.ehu.es/theme/image.php/standard/forum/1419846478/icon" />Novedades del sitio</a></p></li></ul></li>
<li class="type_user depth_2 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch"><span tabindex="0">My profile</span></p><ul><li class="type_custom depth_3 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/user/profile.php?id=11850"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />View profile</a></p></li>
<li class="type_custom depth_3 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch"><span tabindex="0">Forum posts</span></p><ul><li class="type_custom depth_4 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/mod/forum/user.php?id=11850"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Posts</a></p></li>
<li class="type_custom depth_4 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/mod/forum/user.php?id=11850&amp;mode=discussions"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Discussions</a></p></li></ul></li>
<li class="type_unknown depth_3 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch"><span tabindex="0">Blogs</span></p><ul><li class="type_custom depth_4 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/blog/index.php?userid=11850"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />View all of my entries</a></p></li>
<li class="type_custom depth_4 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/blog/edit.php?action=add"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Add a new entry</a></p></li>
<li class="type_setting depth_4 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/rss/file.php/1/b3c0598877f3d9eb21da508bbac86031/blog/user/11850/rss.xml"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/rss" />Blog RSS feed</a></p></li></ul></li>
<li class="type_setting depth_3 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/message/index.php"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Messages</a></p></li>
<li class="type_setting depth_3 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/user/files.php"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />My private files</a></p></li></ul></li>
<li class="type_system depth_2 contains_branch" aria-expanded="true"><p class="tree_item branch"><span tabindex="0">Current course</span></p><ul><li class="type_course depth_3 contains_branch" aria-expanded="true"><p class="tree_item branch canexpand"><a title="Bases de Datos" href="https://egela.ehu.es/course/view.php?id=343">163_GIIGSI10_26020_01</a></p><ul><li class="type_unknown depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch"><a href="https://egela.ehu.es/user/index.php?id=343">Participants</a></p><ul><li class="type_custom depth_5 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/blog/index.php?courseid=343"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Course blogs</a></p></li>
<li class="type_user depth_5 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch"><a href="https://egela.ehu.es/user/view.php?id=11850&amp;course=343">Javier Martín Salvatierra</a></p><ul><li class="type_custom depth_6 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/user/view.php?id=11850&amp;course=343"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />View profile</a></p></li>
<li class="type_custom depth_6 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch"><span tabindex="0">Forum posts</span></p><ul><li class="type_custom depth_7 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/mod/forum/user.php?id=11850&amp;course=343"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Posts</a></p></li>
<li class="type_custom depth_7 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/mod/forum/user.php?id=11850&amp;course=343&amp;mode=discussions"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Discussions</a></p></li></ul></li>
<li class="type_unknown depth_6 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch"><span tabindex="0">Blogs</span></p><ul><li class="type_custom depth_7 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/blog/index.php?userid=11850"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />View all of my entries</a></p></li>
<li class="type_custom depth_7 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/blog/edit.php?action=add"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Add a new entry</a></p></li>
<li class="type_setting depth_7 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/rss/file.php/1/b3c0598877f3d9eb21da508bbac86031/blog/user/11850/rss.xml"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/rss" />Blog RSS feed</a></p></li></ul></li>
<li class="type_setting depth_6 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/message/index.php"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Messages</a></p></li>
<li class="type_setting depth_6 item_with_icon"><p class="tree_item leaf hasicon"><a href="https://egela.ehu.es/user/files.php"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />My private files</a></p></li></ul></li></ul></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3455"><span tabindex="0">General</span></p></li>
<li class="type_structure depth_4 contains_branch" aria-expanded="true"><p class="tree_item branch"><span tabindex="0">Topic 1</span></p><ul><li class="type_activity depth_5 item_with_icon current_branch"><p class="tree_item leaf hasicon active_tree_node"><a title="File" href="https://egela.ehu.es/mod/resource/view.php?id=10351" id="action_link552ff7033de3a1"><img alt="File" class="smallicon navicon" title="File" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/f/pdf-24" />Presentación (Temario, Evaluación....)</a></p></li>
<li class="type_activity depth_5 item_with_icon"><p class="tree_item leaf hasicon"><a title="Page" href="https://egela.ehu.es/mod/page/view.php?id=10353"><img alt="Page" class="smallicon navicon" title="Page" src="https://egela.ehu.es/theme/image.php/standard/page/1419846478/icon" />AVISO IMPORTANTE: SISTEMA DE EVALUACIÓN</a></p></li>
<li class="type_activity depth_5 item_with_icon"><p class="tree_item leaf hasicon"><a title="Page" href="https://egela.ehu.es/mod/page/view.php?id=10354"><img alt="Page" class="smallicon navicon" title="Page" src="https://egela.ehu.es/theme/image.php/standard/page/1419846478/icon" />Semanas con laboratorio</a></p></li></ul></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3458"><span tabindex="0">Topic 2</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3459"><span tabindex="0">Topic 3</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3460"><span tabindex="0">Topic 4</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3461"><span tabindex="0">Topic 5</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3462"><span tabindex="0">Topic 6</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3463"><span tabindex="0">Topic 7</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3457"><span tabindex="0">Topic 8</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3464"><span tabindex="0">Topic 9</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3465"><span tabindex="0">Topic 10</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3468"><span tabindex="0">Topic 13</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3469"><span tabindex="0">Topic 14</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3470"><span tabindex="0">Topic 15</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3471"><span tabindex="0">Topic 16</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3472"><span tabindex="0">Topic 17</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3473"><span tabindex="0">Topic 18</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3474"><span tabindex="0">Topic 19</span></p></li>
<li class="type_structure depth_4 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_30_3475"><span tabindex="0">Topic 20</span></p></li></ul></li></ul></li>
<li class="type_system depth_2 collapsed contains_branch" aria-expanded="false"><p class="tree_item branch" id="expandable_branch_0_mycourses"><a href="https://egela.ehu.es/my/">My courses</a></p></li></ul></li></ul></div></div><span id="sb-1" class="skip-block-to"></span><a href="#sb-2" class="skip-block">Skip Administration</a><div id="inst5" class="block_settings  block" role="navigation" aria-labelledby="instance-5-header"><div class="header"><div class="title"><div class="block_action"></div><h2 id="instance-5-header">Administration</h2></div></div><div class="content"><div id="settingsnav" class="box block_tree_box"><ul class="block_tree list"><li class="type_course collapsed contains_branch" aria-expanded="false"><p class="tree_item branch root_node"><span tabindex="0">Course administration</span></p><ul><li class="type_setting collapsed item_with_icon"><p class="tree_item leaf"><a href="https://egela.ehu.es/grade/report/index.php?id=343"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/grades" />Grades</a></p></li></ul></li>
<li class="type_unknown collapsed contains_branch" aria-expanded="false"><hr /><p class="tree_item branch root_node" id="usersettings"><span tabindex="0">My profile settings</span></p><ul><li class="type_setting collapsed item_with_icon"><p class="tree_item leaf"><a href="https://egela.ehu.es/user/edit.php?id=11850&amp;course=343"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Edit profile</a></p></li>
<li class="type_setting collapsed item_with_icon"><p class="tree_item leaf"><a href="https://egela.ehu.es/user/managetoken.php?sesskey=An6hiqTdTt"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Security keys</a></p></li>
<li class="type_setting collapsed item_with_icon"><p class="tree_item leaf"><a href="https://egela.ehu.es/message/edit.php?id=11850"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Messaging</a></p></li>
<li class="type_unknown collapsed contains_branch" aria-expanded="false"><p class="tree_item branch"><span tabindex="0">Blogs</span></p><ul><li class="type_setting collapsed item_with_icon"><p class="tree_item leaf"><a href="https://egela.ehu.es/blog/preferences.php"><img alt="" class="smallicon navicon" title="" src="https://egela.ehu.es/theme/image.php/standard/core/1419846478/i/navigationitem" />Preferences</a></p></li></ul></li></ul></li></ul></div></div></div><span id="sb-2" class="skip-block-to"></span>
                    </div>
                </div>
                
                
            </div>
        </div>
    </div>

<!-- START OF FOOTER -->
            <div id="page-footer" class="clearfix">
        <p class="helplink"></p>
        <div class="logininfo">You are logged in as <a href="https://egela.ehu.es/user/profile.php?id=11850" title="View profile">Javier Martín Salvatierra</a> (<a href="https://egela.ehu.es/login/logout.php?sesskey=An6hiqTdTt">Logout</a>)</div><div class="homelink"><a href="https://egela.ehu.es/course/view.php?id=343">163_GIIGSI10_26020_01</a></div>    </div>
        <div class="clearfix"></div>
</div>
<script type="text/javascript">
//<![CDATA[
M.str = {"moodle":{"lastmodified":"Last modified","name":"Name","error":"Error","info":"Information","viewallcourses":"View all courses","morehelp":"More help","loadinghelp":"Loading...","cancel":"Cancel","yes":"Yes"},"repository":{"type":"Type","size":"Size","invalidjson":"Invalid JSON string","nofilesattached":"No files attached","filepicker":"File picker","logout":"Logout","nofilesavailable":"No files available","norepositoriesavailable":"Sorry, none of your current repositories can return files in the required format.","fileexistsdialogheader":"File exists","fileexistsdialog_editor":"A file with that name has already been attached to the text you are editing.","fileexistsdialog_filemanager":"A file with that name has already been attached","renameto":"Rename to \"{$a}\"","referencesexist":"There are {$a} alias\/shortcut files that use this file as their source","select":"Select"},"block":{"addtodock":"Move this to the dock","undockitem":"Undock this item","dockblock":"Dock {$a} block","undockblock":"Undock {$a} block","undockall":"Undock all","hidedockpanel":"Hide the dock panel","hidepanel":"Hide panel"},"langconfig":{"thisdirectionvertical":"btt"},"admin":{"confirmation":"Confirmation"}};
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
var navtreeexpansions4 = [{"id":"expandable_branch_30_3455","key":"3455","type":30},{"id":"expandable_branch_30_3458","key":"3458","type":30},{"id":"expandable_branch_30_3459","key":"3459","type":30},{"id":"expandable_branch_30_3460","key":"3460","type":30},{"id":"expandable_branch_30_3461","key":"3461","type":30},{"id":"expandable_branch_30_3462","key":"3462","type":30},{"id":"expandable_branch_30_3463","key":"3463","type":30},{"id":"expandable_branch_30_3457","key":"3457","type":30},{"id":"expandable_branch_30_3464","key":"3464","type":30},{"id":"expandable_branch_30_3465","key":"3465","type":30},{"id":"expandable_branch_30_3468","key":"3468","type":30},{"id":"expandable_branch_30_3469","key":"3469","type":30},{"id":"expandable_branch_30_3470","key":"3470","type":30},{"id":"expandable_branch_30_3471","key":"3471","type":30},{"id":"expandable_branch_30_3472","key":"3472","type":30},{"id":"expandable_branch_30_3473","key":"3473","type":30},{"id":"expandable_branch_30_3474","key":"3474","type":30},{"id":"expandable_branch_30_3475","key":"3475","type":30},{"id":"expandable_branch_0_mycourses","key":"mycourses","type":0}];
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
YUI().use('node', function(Y) {
M.util.load_flowplayer();
setTimeout("fix_column_widths()", 20);
M.yui.galleryversion="2010.04.08-12-35";Y.use("moodle-filter_glossary-autolinker",function() {M.filter_glossary.init_filter_autolinking({"courseid":0});
});
function legacy_activity_onclick_handler_1(e) { e.halt(); window.open('https://egela.ehu.es/mod/resource/view.php?id=10351&redirect=1', '', 'width=620,height=450,toolbar=no,location=no,menubar=no,copyhistory=no,status=no,directories=no,scrollbars=yes,resizable=yes'); return false; };
M.yui.galleryversion="2010.04.08-12-35";Y.use("core_dock","moodle-block_navigation-navigation",function() {M.block_navigation.init_add_tree({"id":"4","instance":"4","candock":true,"courselimit":"20","expansionlimit":0});
});
M.yui.galleryversion="2010.04.08-12-35";Y.use("core_dock","moodle-block_navigation-navigation",function() {M.block_navigation.init_add_tree({"id":"5","instance":"5","candock":true});
});
M.util.help_popups.setup(Y);
M.yui.galleryversion="2010.04.08-12-35";Y.use("moodle-core-popuphelp",function() {M.core.init_popuphelp();
});
M.util.init_block_hider(Y, {"id":"inst4","title":"Navigation","preference":"block4hidden","tooltipVisible":"Hide Navigation block","tooltipHidden":"Show Navigation block"});
M.util.init_block_hider(Y, {"id":"inst5","title":"Administration","preference":"block5hidden","tooltipVisible":"Hide Administration block","tooltipHidden":"Show Administration block"});
Y.on('click', legacy_activity_onclick_handler_1, "#action_link552ff7033de3a1", null);
Y.on('click', legacy_activity_onclick_handler_1, "#action_link552ff7033de3a2", null);

});
//]]>
</script>
</body>
</html>